version: 2
jobs:
  install:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}

      - run:
          name: Install dependancies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:latest-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}

      - run:
          name: Run Tests
          command: npm run test

  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    environment:
      - NODE_ENV: "production"

    steps:
      - checkout

      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}

      - run:
          name: Build
          command: npm run build

workflows:
  version: 2
  test-and-build:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
            - test
