window.esdocSearchIndex = [
  [
    "regexp-events/src/emitter.js~emitter",
    "class/src/Emitter.js~Emitter.html",
    "<span>Emitter</span> <span class=\"search-result-import-path\">regexp-events/src/Emitter.js</span>",
    "class"
  ],
  [
    "regexp-events/src/event.js~event",
    "class/src/Event.js~Event.html",
    "<span>Event</span> <span class=\"search-result-import-path\">regexp-events/src/Event.js</span>",
    "class"
  ],
  [
    "regexp-events/src/utils.js~clearlisteners",
    "function/index.html#static-function-clearListeners",
    "<span>clearListeners</span> <span class=\"search-result-import-path\">regexp-events/src/utils.js</span>",
    "function"
  ],
  [
    "regexp-events/src/utils.js~isregexpequal",
    "function/index.html#static-function-isRegExpEqual",
    "<span>isRegExpEqual</span> <span class=\"search-result-import-path\">regexp-events/src/utils.js</span>",
    "function"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber34",
    "Emitter",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber366",
    "Emitter clear",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber376",
    "Emitter clear () dose not remove static listeners",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber367",
    "Emitter clear () removes all listeners",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber418",
    "Emitter clear (Event) removes all listeners of event type",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber425",
    "Emitter clear (RegExp) removes listeners with matching String or same RegExp",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber433",
    "Emitter clear (RegExp, force=false, useRegexp=false) only removes matching RegExp",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber441",
    "Emitter clear (RegExp, force=false, useRegexp=false) takes RegExp flags into account when comparing regexes",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber397",
    "Emitter clear (String) removes all listeners of type",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber411",
    "Emitter clear (String, force=false) dose not remove static listeners of type",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber404",
    "Emitter clear (String, force=true) removes static listeners of type",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber390",
    "Emitter clear (force=false) dose not remove static listeners",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber383",
    "Emitter clear (force=true) removes static listeners",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber450",
    "Emitter count",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber457",
    "Emitter count () returns total number of all listeners on the emitter",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber470",
    "Emitter count (Event) returns number of listeners of Event.type",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber477",
    "Emitter count (RegExp) returns number of listeners that match the RegExp",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber487",
    "Emitter count (RegExp, useRegExp=false) returns number of listeners that have a identical RegExp",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber463",
    "Emitter count (String) returns number of listeners of that type",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber451",
    "Emitter count should return 0 if eventMap has not been created yet",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber42",
    "Emitter createEventMap",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber43",
    "Emitter createEventMap should create an eventMap if one dose not exist",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber51",
    "Emitter createEventMap should not create a new events map if one exists",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber580",
    "Emitter dispose",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber581",
    "Emitter dispose should call Emitter.removeEventMap",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber505",
    "Emitter emit",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber532",
    "Emitter emit (Event) calls listeners",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber545",
    "Emitter emit (Event) calls listeners with Event.args",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber538",
    "Emitter emit (Event) emits the Event that is passed in",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber552",
    "Emitter emit (Event) sets Event.target if its not already set",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber513",
    "Emitter emit (String) calls listeners",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber519",
    "Emitter emit (String, args...) calls listeners with arguments",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber525",
    "Emitter emit (String, args...) passes the Event as the last arguments",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber565",
    "Emitter emit dost not fire the event if Emitter.suppressEvents == true",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber572",
    "Emitter emit removes listener after calling is the correct number of times",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber506",
    "Emitter emit throws error if eventType is not a string",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber280",
    "Emitter off",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber315",
    "Emitter off (Event, Function) removes listener",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber321",
    "Emitter off (RegExp, Function) removes listener",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber293",
    "Emitter off (String, Function) dose not remove static listener",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber306",
    "Emitter off (String, Function) dost not remove listener with different context",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber288",
    "Emitter off (String, Function) removes listener",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber299",
    "Emitter off (String, Function, context) removes listener with context",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber345",
    "Emitter off (String, Function, context, force=false) dose not remove static listener",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber339",
    "Emitter off (String, Function, context, force=true) removes static listener",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber333",
    "Emitter off (String, Function, force=false) dose not remove static listener",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber358",
    "Emitter off (String, Function, force=false, context) dose not remove static listener",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber328",
    "Emitter off (String, Function, force=true) removes static listener",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber352",
    "Emitter off (String, Function, force=true, context) removes static listener",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber281",
    "Emitter off only removes the first listener that matches",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber70",
    "Emitter on",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber247",
    "Emitter on () throws if there is no event type",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber239",
    "Emitter on (Event, Function)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber253",
    "Emitter on (Number|Null|Function) throws if the eventType is not a String, Event or RegExp",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber230",
    "Emitter on (RegExp, Function)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber267",
    "Emitter on (String) throws if listener function is no provided",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber71",
    "Emitter on (String, Function)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber81",
    "Emitter on (String, Function, context)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber111",
    "Emitter on (String, Function, context, isStatic)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber121",
    "Emitter on (String, Function, context, isStatic, times)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber91",
    "Emitter on (String, Function, context, times)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber101",
    "Emitter on (String, Function, context, times, isStatic)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber132",
    "Emitter on (String, Function, isStatic)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber141",
    "Emitter on (String, Function, isStatic, context)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber160",
    "Emitter on (String, Function, isStatic, context, times)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber151",
    "Emitter on (String, Function, isStatic, times)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber170",
    "Emitter on (String, Function, isStatic, times, context)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber181",
    "Emitter on (String, Function, times)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber190",
    "Emitter on (String, Function, times, context)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber209",
    "Emitter on (String, Function, times, context, isStatic)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber200",
    "Emitter on (String, Function, times, isStatic)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber219",
    "Emitter on (String, Function, times, isStatic, context)",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber273",
    "Emitter on (String, Null) throws if listener is not a function",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber496",
    "Emitter once",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber497",
    "Emitter once removes listener after the event is fired",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber60",
    "Emitter removeEventMap",
    "test"
  ],
  [
    "",
    "test-file/test/Emitter.spec.js.html#lineNumber61",
    "Emitter removeEventMap should not create an eventMap if one dose not exist",
    "test"
  ],
  [
    "",
    "test-file/test/Event.spec.js.html#lineNumber4",
    "Event",
    "test"
  ],
  [
    "",
    "test-file/test/Event.spec.js.html#lineNumber5",
    "Event constructor",
    "test"
  ],
  [
    "",
    "test-file/test/Event.spec.js.html#lineNumber24",
    "Event constructor (String) should return an Event",
    "test"
  ],
  [
    "",
    "test-file/test/Event.spec.js.html#lineNumber28",
    "Event constructor should set args to an empty array if not passed in",
    "test"
  ],
  [
    "",
    "test-file/test/Event.spec.js.html#lineNumber6",
    "Event constructor should throw an error if type is not a string",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/emitter.js",
    "file/src/Emitter.js.html",
    "src/Emitter.js",
    "file"
  ],
  [
    "src/emitter.js~emitter#clear",
    "class/src/Emitter.js~Emitter.html#instance-method-clear",
    "src/Emitter.js~Emitter#clear",
    "method"
  ],
  [
    "src/emitter.js~emitter#constructor",
    "class/src/Emitter.js~Emitter.html#instance-constructor-constructor",
    "src/Emitter.js~Emitter#constructor",
    "method"
  ],
  [
    "src/emitter.js~emitter#count",
    "class/src/Emitter.js~Emitter.html#instance-method-count",
    "src/Emitter.js~Emitter#count",
    "method"
  ],
  [
    "src/emitter.js~emitter#dispose",
    "class/src/Emitter.js~Emitter.html#instance-method-dispose",
    "src/Emitter.js~Emitter#dispose",
    "method"
  ],
  [
    "src/emitter.js~emitter#emit",
    "class/src/Emitter.js~Emitter.html#instance-method-emit",
    "src/Emitter.js~Emitter#emit",
    "method"
  ],
  [
    "src/emitter.js~emitter#eventmap",
    "class/src/Emitter.js~Emitter.html#instance-get-eventMap",
    "src/Emitter.js~Emitter#eventMap",
    "member"
  ],
  [
    "src/emitter.js~emitter#off",
    "class/src/Emitter.js~Emitter.html#instance-method-off",
    "src/Emitter.js~Emitter#off",
    "method"
  ],
  [
    "src/emitter.js~emitter#on",
    "class/src/Emitter.js~Emitter.html#instance-method-on",
    "src/Emitter.js~Emitter#on",
    "method"
  ],
  [
    "src/emitter.js~emitter#once",
    "class/src/Emitter.js~Emitter.html#instance-method-once",
    "src/Emitter.js~Emitter#once",
    "method"
  ],
  [
    "src/emitter.js~emitter#suppressevents",
    "class/src/Emitter.js~Emitter.html#instance-member-suppressEvents",
    "src/Emitter.js~Emitter#suppressEvents",
    "member"
  ],
  [
    "src/emitter.js~emitter.createeventmap",
    "class/src/Emitter.js~Emitter.html#static-method-createEventMap",
    "src/Emitter.js~Emitter.createEventMap",
    "method"
  ],
  [
    "src/emitter.js~emitter.geteventmap",
    "class/src/Emitter.js~Emitter.html#static-method-getEventMap",
    "src/Emitter.js~Emitter.getEventMap",
    "method"
  ],
  [
    "src/emitter.js~emitter.removeeventmap",
    "class/src/Emitter.js~Emitter.html#static-method-removeEventMap",
    "src/Emitter.js~Emitter.removeEventMap",
    "method"
  ],
  [
    "src/event.js",
    "file/src/Event.js.html",
    "src/Event.js",
    "file"
  ],
  [
    "src/event.js~event#args",
    "class/src/Event.js~Event.html#instance-member-args",
    "src/Event.js~Event#args",
    "member"
  ],
  [
    "src/event.js~event#constructor",
    "class/src/Event.js~Event.html#instance-constructor-constructor",
    "src/Event.js~Event#constructor",
    "method"
  ],
  [
    "src/event.js~event#target",
    "class/src/Event.js~Event.html#instance-member-target",
    "src/Event.js~Event#target",
    "member"
  ],
  [
    "src/event.js~event#type",
    "class/src/Event.js~Event.html#instance-member-type",
    "src/Event.js~Event#type",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/utils.js",
    "file/src/utils.js.html",
    "src/utils.js",
    "file"
  ],
  [
    "test/emitter.spec.js",
    "test-file/test/Emitter.spec.js.html",
    "test/Emitter.spec.js",
    "testFile"
  ],
  [
    "test/event.spec.js",
    "test-file/test/Event.spec.js.html",
    "test/Event.spec.js",
    "testFile"
  ]
]